name: Backend unit testing

on:
  push:
    branches: [integrate-github-action]

defaults:
  run:
    working-directory: backend

jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
        - 3306:3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD:
          MYSQL_DATABASE: SmartEasyTravelTest
          MYSQL_ROOT_PASSWORD:
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
        NODE_ENV: test
